version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Makie"
      - dependency-name: "CairoMakie"
    groups:
      all-julia-packages:
        patterns:
          - "*"
        exclude-patterns:
          - "Makie"
          - "CairoMakie"
